# TinyORM library header and source files
# Create header and source files lists and return them
function(tiny_sources)

    set(headers
        basegrammar.hpp
        concepts.hpp
        concerns/detectslostconnections.hpp
        concerns/hasconnectionresolver.hpp
        configuration.hpp
        connectioninterface.hpp
        connectionresolverinterface.hpp
        connectors/connectionfactory.hpp
        connectors/connector.hpp
        connectors/connectorinterface.hpp
        connectors/mysqlconnector.hpp
        connectors/postgresconnector.hpp
        connectors/sqliteconnector.hpp
        constants.hpp
        databaseconnection.hpp
        databasemanager.hpp
        db.hpp
        exceptions/domainerror.hpp
        exceptions/invalidargumenterror.hpp
        exceptions/invalidformaterror.hpp
        exceptions/invalidtemplateargumenterror.hpp
        exceptions/logicerror.hpp
        exceptions/queryerror.hpp
        exceptions/runtimeerror.hpp
        exceptions/sqlerror.hpp
        exceptions/sqltransactionerror.hpp
        logquery.hpp
        macros.hpp
        mysqlconnection.hpp
        ormtypes.hpp
        postgresconnection.hpp
        query/expression.hpp
        query/grammars/grammar.hpp
        query/grammars/mysqlgrammar.hpp
        query/grammars/postgresgrammar.hpp
        query/grammars/sqlitegrammar.hpp
        query/joinclause.hpp
        query/processors/mysqlprocessor.hpp
        query/processors/postgresprocessor.hpp
        query/processors/processor.hpp
        query/processors/sqliteprocessor.hpp
        query/querybuilder.hpp
        schema/grammars/mysqlschemagrammar.hpp
        schema/grammars/postgresschemagrammar.hpp
        schema/grammars/schemagrammar.hpp
        schema/grammars/sqliteschemagrammar.hpp
        schema/mysqlschemabuilder.hpp
        schema/postgresschemabuilder.hpp
        schema/schemabuilder.hpp
        schema/sqliteschemabuilder.hpp
        sqliteconnection.hpp
        support/configurationoptionsparser.hpp
        tiny/concerns/guardsattributes.hpp
        tiny/concerns/hasattributes.hpp
        tiny/concerns/hasrelationstore.hpp
        tiny/concerns/queriesrelationships.hpp
        tiny/exceptions/massassignmenterror.hpp
        tiny/exceptions/modelnotfounderror.hpp
        tiny/exceptions/relationnotfounderror.hpp
        tiny/exceptions/relationnotloadederror.hpp
        tiny/model.hpp
        tiny/modelproxies.hpp
        tiny/relations/basepivot.hpp
        tiny/relations/belongsto.hpp
        tiny/relations/belongstomany.hpp
        tiny/relations/concerns/supportsdefaultmodels.hpp
        tiny/relations/hasmany.hpp
        tiny/relations/hasone.hpp
        tiny/relations/hasoneormany.hpp
        tiny/relations/pivot.hpp
        tiny/relations/relation.hpp
        tiny/relations/relationproxies.hpp
        tiny/tinybuilder.hpp
        tiny/tinybuilderproxies.hpp
        tiny/tinytypes.hpp
        types/log.hpp
        types/statementscounter.hpp
        utils/attribute.hpp
        utils/export.hpp
        utils/string.hpp
        utils/type.hpp
#        version.hpp
    )

    set(sources
        basegrammar.cpp
        concerns/detectslostconnections.cpp
        concerns/hasconnectionresolver.cpp
        connectors/connectionfactory.cpp
        connectors/connector.cpp
        connectors/mysqlconnector.cpp
        connectors/postgresconnector.cpp
        connectors/sqliteconnector.cpp
        constants.cpp
        databaseconnection.cpp
        databasemanager.cpp
        db.cpp
        exceptions/logicerror.cpp
        exceptions/queryerror.cpp
        exceptions/runtimeerror.cpp
        exceptions/sqlerror.cpp
        logquery.cpp
        mysqlconnection.cpp
        ormtypes.cpp
        postgresconnection.cpp
        query/expression.cpp
        query/grammars/grammar.cpp
        query/grammars/mysqlgrammar.cpp
        query/grammars/postgresgrammar.cpp
        query/grammars/sqlitegrammar.cpp
        query/joinclause.cpp
        query/processors/mysqlprocessor.cpp
        query/processors/postgresprocessor.cpp
        query/processors/processor.cpp
        query/processors/sqliteprocessor.cpp
        query/querybuilder.cpp
        schema/grammars/mysqlschemagrammar.cpp
        schema/grammars/postgresschemagrammar.cpp
        schema/grammars/schemagrammar.cpp
        schema/grammars/sqliteschemagrammar.cpp
        schema/mysqlschemabuilder.cpp
        schema/postgresschemabuilder.cpp
        schema/schemabuilder.cpp
        schema/sqliteschemabuilder.cpp
        sqliteconnection.cpp
        support/configurationoptionsparser.cpp
        tiny/model.cpp
        tiny/exceptions/modelnotfounderror.cpp
        tiny/exceptions/relationnotfounderror.cpp
        tiny/exceptions/relationnotloadederror.cpp
        tiny/relations/relation.cpp
        utils/attribute.cpp
        utils/string.cpp
        utils/type.cpp
    )

    list(TRANSFORM headers PREPEND "include/orm/")
    list(TRANSFORM sources PREPEND "src/orm/")

    set(headers ${headers} PARENT_SCOPE)
    set(sources ${sources} PARENT_SCOPE)

endfunction()
